// Variables
@hostname = http://localhost
@port = 8000

###
// Root - returns available api calls
GET {{hostname}}:{{port}} HTTP/1.1

###
// READ - To get metadata of books (with specified limit)
// Skip: skip to which document count (multipled of limit), Limit: return how many books
// note under the hood it does this: db.metadata.find().skip(5).limit(5)
POST {{hostname}}:{{port}}/api/get_metadatas HTTP/1.1
content-type: application/json
{
    "skip": 5,
    "limit" 5
}

###
// READ - To get metadata of a particular book
POST {{hostname}}:{{port}}/api/get_metadatas HTTP/1.1
content-type: application/json
{
    "asin": "B000F83SZQ",
}


###
// CREATE - add a book
POST {{hostname}}:{{port}}/api/add_book HTTP/1.1
content-type: application/json
{
    "asin": "B0001234ZZ",
    "title": "Black Book",
    "description": "This is description of this item",
    "price": "9.9",
    "imUrl": "https://miro.medium.com/max/1400/1*4PrMNL-FF9Z5G5BXJliAYg.png",
    "related": {"also_bought":[], "buy_after_viewing":[]},
    "categories": [['Books', 'Literature & Fiction']],
}
###
###
// DELETE - remove a book
POST {{hostname}}:{{port}}/api/delete_book HTTP/1.1
content-type: application/json
{
    "asin": "B0001234ZZ",
}
###
// READ - get the image urls of related images
POST {{hostname}}:{{port}}/api/related_images HTTP/1.1
content-type: application/json
{
    "asin_list": ["B0001234ZZ", "B0001234ZZ"]
}
###
